GOOGLE_API_KEY = "AIzaSyAN82T0JeICs56P7tBCTcSIcbdNGwwsvms"
PINECONE_API_KEY = "pcsk_4Mmneg_SmSzJRZU1PGro9Zi297vrJYM22HCNWEHxZKaqDz1LtjoxvMqoLBbyY9Gj4kt5Sm"
LANGSMITH_API_KEY = "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"
MYSQL_SERVICE_URI = "mysql://avnadmin:AVNS_widGK1BYBUQ_QCTkBq5@ai-case-nileshtiwari6388261059-cc65.l.aivencloud.com:10849/defaultdb?ssl-mode=REQUIRED"
MYSQL_DATABASE = "defaultdb"
MYSQL_USER = "avnadmin"
MYSQL_PASSWORD = "AVNS_widGK1BYBUQ_QCTkBq5"
MYSQL_HOST = "ai-case-nileshtiwari6388261059-cc65.l.aivencloud.com"
MYSQL_PORT = "10849"
INDEX_NAME = "4bca102a"